/*
Copyright © 2024 netcfg authors

802.1X / EAP 支持：从 netplan auth 块生成 wpa_supplicant 配置和 systemd unit。
内核不做 EAP，认证必须由 wpa_supplicant 完成；netcfg 采用"生成配置 + 交给
systemd 启动"的方式（不在自身进程内管理 supplicant 生命周期）。
*/

package cmd

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"syscall"

	"github.com/netcfg/netcfg/config"
)

const (
	wpaConfDir   = "/etc/netcfg"
	wpaSupBinary = "wpa_supplicant"
)

// setup8021x 为接口生成 wpa_supplicant 配置与 systemd unit，并尽力 enable 启动。
// 仅当 key-management 为 802.1x 或 eap* 时处理（psk/sae 属 WiFi，由 WiFi 路径负责）。
func setup8021x(name string, auth *config.Auth) {
	km := strings.ToLower(auth.KeyManagement)
	if km != "802.1x" && !strings.HasPrefix(km, "eap") {
		return
	}

	conf := buildWPASupplicantConf(km, auth)
	confPath := fmt.Sprintf("%s/wpa-%s.conf", wpaConfDir, name)

	// 配置含密钥/密码，权限 0600
	if err := os.MkdirAll(wpaConfDir, 0755); err != nil {
		slog.Warn("failed to create wpa conf dir", "error", err)
		return
	}
	if err := os.WriteFile(confPath, []byte(conf), 0600); err != nil {
		slog.Warn("failed to write wpa_supplicant config", "device", name, "error", err)
		return
	}
	slog.Info("wrote 802.1x wpa_supplicant config", "device", name, "path", confPath)

	// 直接拉起 wpa_supplicant（有线驱动）。init-agnostic，与外部 DHCP 客户端一致。
	runSupplicant(name, "wired", confPath)
}

// runSupplicant 直接（后台）启动 wpa_supplicant，不依赖任何 init 系统。
// driver: 有线用 "wired"，WiFi 用 "nl80211"。检测不到 wpa_supplicant 时仅告警
// （配置已写，装上后重新 apply 即可）。先停掉该接口已有的实例以保证幂等。
func runSupplicant(iface, driver, confPath string) {
	stopSupplicant(iface)

	bin, err := exec.LookPath(wpaSupBinary)
	if err != nil {
		slog.Warn("wpa_supplicant not found; config written but supplicant not started (install wpa_supplicant)",
			"interface", iface, "conf", confPath)
		return
	}

	pidFile := supplicantPidFile(iface)
	// -B 后台化；-P 写 pidfile，供后续停止/幂等
	cmd := exec.Command(bin, "-B", "-D", driver, "-i", iface, "-c", confPath, "-P", pidFile)
	if out, err := cmd.CombinedOutput(); err != nil {
		slog.Warn("failed to start wpa_supplicant", "interface", iface, "driver", driver,
			"error", err, "output", strings.TrimSpace(string(out)))
		return
	}
	slog.Info("started wpa_supplicant", "interface", iface, "driver", driver)
}

// stopSupplicant 按 pidfile 停止接口上的 wpa_supplicant（不存在则无操作）。
func stopSupplicant(iface string) {
	pidFile := supplicantPidFile(iface)
	data, err := os.ReadFile(pidFile)
	if err != nil {
		return
	}
	if pid, err := strconv.Atoi(strings.TrimSpace(string(data))); err == nil {
		if proc, err := os.FindProcess(pid); err == nil {
			_ = proc.Signal(syscall.SIGTERM)
		}
	}
	_ = os.Remove(pidFile)
}

func supplicantPidFile(iface string) string {
	return fmt.Sprintf("/run/netcfg-wpa-%s.pid", iface)
}

// buildWPASupplicantConf 把 auth 块渲染为 wpa_supplicant.conf。
func buildWPASupplicantConf(km string, auth *config.Auth) string {
	var b strings.Builder
	b.WriteString("# Generated by netcfg\n")
	b.WriteString("ctrl_interface=/run/wpa_supplicant\n")
	b.WriteString("eapol_version=1\n")
	b.WriteString("ap_scan=0\n")
	b.WriteString("network={\n")

	// 有线 802.1x 用 IEEE8021X；eap（无线企业）用 WPA-EAP
	if km == "802.1x" {
		b.WriteString("\tkey_mgmt=IEEE8021X\n")
	} else {
		b.WriteString("\tkey_mgmt=WPA-EAP\n")
	}

	writeEAPFields(&b, auth)

	b.WriteString("}\n")
	return b.String()
}

// writeEAPFields 把 EAP/证书相关字段写入 wpa_supplicant network={} 块（不含 key_mgmt，
// 由调用方按有线 802.1x / WiFi 决定）。供有线 802.1x 与 WiFi 企业认证共用。
func writeEAPFields(b *strings.Builder, auth *config.Auth) {
	if auth.Method != "" {
		b.WriteString("\teap=" + strings.ToUpper(auth.Method) + "\n")
	}
	writeQuoted(b, "identity", auth.Identity)
	writeQuoted(b, "anonymous_identity", auth.AnonymousIdentity)
	writeQuoted(b, "password", auth.Password)
	writeQuoted(b, "ca_cert", auth.CACertificate)
	writeQuoted(b, "client_cert", auth.ClientCertificate)
	writeQuoted(b, "private_key", auth.ClientKey)
	writeQuoted(b, "private_key_passwd", auth.ClientKeyPassword)
	if auth.Phase2Auth != "" {
		b.WriteString("\tphase2=\"auth=" + auth.Phase2Auth + "\"\n")
	}
}

func writeQuoted(b *strings.Builder, key, val string) {
	if val != "" {
		b.WriteString("\t" + key + "=\"" + val + "\"\n")
	}
}
