/*
Copyright © 2024 netcfg authors

802.1X / EAP 支持：从 netplan auth 块生成 wpa_supplicant 配置和 systemd unit。
内核不做 EAP，认证必须由 wpa_supplicant 完成；netcfg 采用"生成配置 + 交给
systemd 启动"的方式（不在自身进程内管理 supplicant 生命周期）。
*/

package cmd

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strings"

	"github.com/netcfg/netcfg/config"
)

const (
	wpaConfDir   = "/etc/netcfg"
	systemdDir   = "/etc/systemd/system"
	wpaSupBinary = "wpa_supplicant"
)

// setup8021x 为接口生成 wpa_supplicant 配置与 systemd unit，并尽力 enable 启动。
// 仅当 key-management 为 802.1x 或 eap* 时处理（psk/sae 属 WiFi，由 WiFi 路径负责）。
func setup8021x(name string, auth *config.Auth) {
	km := strings.ToLower(auth.KeyManagement)
	if km != "802.1x" && !strings.HasPrefix(km, "eap") {
		return
	}

	conf := buildWPASupplicantConf(km, auth)
	confPath := fmt.Sprintf("%s/wpa-%s.conf", wpaConfDir, name)
	unitName := fmt.Sprintf("netcfg-8021x-%s.service", name)
	unitPath := fmt.Sprintf("%s/%s", systemdDir, unitName)

	// 配置含密钥/密码，权限 0600
	if err := os.MkdirAll(wpaConfDir, 0755); err != nil {
		slog.Warn("failed to create wpa conf dir", "error", err)
		return
	}
	if err := os.WriteFile(confPath, []byte(conf), 0600); err != nil {
		slog.Warn("failed to write wpa_supplicant config", "device", name, "error", err)
		return
	}
	slog.Info("wrote 802.1x wpa_supplicant config", "device", name, "path", confPath)

	unit := buildDot1xUnit(name, confPath)
	if err := os.WriteFile(unitPath, []byte(unit), 0644); err != nil {
		slog.Warn("failed to write 802.1x systemd unit", "device", name, "error", err)
		return
	}

	if _, err := exec.LookPath(wpaSupBinary); err != nil {
		slog.Warn("wpa_supplicant not found; 802.1x will not authenticate until installed",
			"device", name)
	}

	// 交给 systemd 启动（best-effort：容器/无 systemd 环境下仅告警，不影响 apply）
	_ = exec.Command("systemctl", "daemon-reload").Run()
	if out, err := exec.Command("systemctl", "enable", "--now", unitName).CombinedOutput(); err != nil {
		slog.Warn("failed to enable 802.1x unit via systemd (config/unit written; start manually if needed)",
			"unit", unitName, "error", err, "output", strings.TrimSpace(string(out)))
	} else {
		slog.Info("802.1x supplicant enabled via systemd", "device", name, "unit", unitName)
	}
}

// buildWPASupplicantConf 把 auth 块渲染为 wpa_supplicant.conf。
func buildWPASupplicantConf(km string, auth *config.Auth) string {
	var b strings.Builder
	b.WriteString("# Generated by netcfg\n")
	b.WriteString("ctrl_interface=/run/wpa_supplicant\n")
	b.WriteString("eapol_version=1\n")
	b.WriteString("ap_scan=0\n")
	b.WriteString("network={\n")

	// 有线 802.1x 用 IEEE8021X；eap（无线企业）用 WPA-EAP
	if km == "802.1x" {
		b.WriteString("\tkey_mgmt=IEEE8021X\n")
	} else {
		b.WriteString("\tkey_mgmt=WPA-EAP\n")
	}

	writeEAPFields(&b, auth)

	b.WriteString("}\n")
	return b.String()
}

// writeEAPFields 把 EAP/证书相关字段写入 wpa_supplicant network={} 块（不含 key_mgmt，
// 由调用方按有线 802.1x / WiFi 决定）。供有线 802.1x 与 WiFi 企业认证共用。
func writeEAPFields(b *strings.Builder, auth *config.Auth) {
	if auth.Method != "" {
		b.WriteString("\teap=" + strings.ToUpper(auth.Method) + "\n")
	}
	writeQuoted(b, "identity", auth.Identity)
	writeQuoted(b, "anonymous_identity", auth.AnonymousIdentity)
	writeQuoted(b, "password", auth.Password)
	writeQuoted(b, "ca_cert", auth.CACertificate)
	writeQuoted(b, "client_cert", auth.ClientCertificate)
	writeQuoted(b, "private_key", auth.ClientKey)
	writeQuoted(b, "private_key_passwd", auth.ClientKeyPassword)
	if auth.Phase2Auth != "" {
		b.WriteString("\tphase2=\"auth=" + auth.Phase2Auth + "\"\n")
	}
}

func writeQuoted(b *strings.Builder, key, val string) {
	if val != "" {
		b.WriteString("\t" + key + "=\"" + val + "\"\n")
	}
}

// buildDot1xUnit 生成运行 wpa_supplicant（有线驱动）的 systemd unit。
func buildDot1xUnit(iface, confPath string) string {
	return fmt.Sprintf(`# Generated by netcfg
[Unit]
Description=netcfg 802.1X supplicant for %s
After=netcfg.service
Before=network-online.target
Wants=network.target

[Service]
Type=simple
ExecStart=/sbin/wpa_supplicant -D wired -i %s -c %s
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
`, iface, iface, confPath)
}
