/*
Copyright © 2024 netcfg authors

WiFi 支持：从 netplan wifis 块生成 wpa_supplicant 配置（-D nl80211）+ systemd unit，
并对 wlan 设备应用常规地址/路由/DHCP（复用以太网路径）。
内核不做 WiFi 关联/EAP，必须由 wpa_supplicant 完成；netcfg 只生成配置交给 systemd。
*/

package cmd

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strings"

	"github.com/netcfg/netcfg/config"
	nl "github.com/netcfg/netcfg/netlink"
)

// setupWifis 配置无线设备。
func setupWifis(mgr *nl.NetlinkManager, nsName string, devices map[string]*config.Wifi) error {
	for _, name := range sortedKeys(devices) {
		cfg := devices[name]

		// wlan 物理设备由 netcfg 无法创建：缺失则告警跳过
		if !mgr.LinkExists(name) {
			slog.Warn("wifi device not present; skipping", "device", name)
			continue
		}

		// 监管域（best-effort，需要 iw）
		if cfg.RegulatoryDomain != "" {
			if _, err := exec.LookPath("iw"); err == nil {
				_ = exec.Command("iw", "reg", "set", cfg.RegulatoryDomain).Run()
			} else {
				slog.Warn("iw not found; cannot set regulatory-domain", "device", name)
			}
		}

		// 生成 wpa_supplicant 配置 + systemd unit（交给 systemd 启动）
		setupWifiSupplicant(name, cfg)

		// 设备级地址/路由/DHCP：复用以太网配置路径
		if err := setupDeviceWithDHCP(mgr, name, wifiToEthernet(cfg)); err != nil {
			slog.Warn("failed to setup wifi device", "device", name, "error", err)
		}
	}
	return nil
}

// wifiToEthernet 把 Wifi 的设备级字段映射为 Ethernet，以复用地址/路由/DHCP 逻辑。
func wifiToEthernet(w *config.Wifi) *config.Ethernet {
	return &config.Ethernet{
		Addresses:   w.Addresses,
		DHCP4:       w.DHCP4,
		DHCP6:       w.DHCP6,
		Gateway4:    w.Gateway4,
		Gateway6:    w.Gateway6,
		MTU:         w.MTU,
		Routes:      w.Routes,
		Nameservers: w.Nameservers,
		AcceptRA:    w.AcceptRA,
		LinkLocal:   w.LinkLocal,
	}
}

// setupWifiSupplicant 生成 wpa_supplicant.conf（每个 AP 一个 network 块）+ systemd unit。
func setupWifiSupplicant(name string, cfg *config.Wifi) {
	if len(cfg.AccessPoints) == 0 {
		return
	}

	conf := buildWifiSupplicantConf(cfg)
	confPath := fmt.Sprintf("%s/wpa-%s.conf", wpaConfDir, name)

	if err := os.MkdirAll(wpaConfDir, 0755); err != nil {
		slog.Warn("failed to create wpa conf dir", "error", err)
		return
	}
	if err := os.WriteFile(confPath, []byte(conf), 0600); err != nil {
		slog.Warn("failed to write wifi wpa_supplicant config", "device", name, "error", err)
		return
	}
	slog.Info("wrote wifi wpa_supplicant config", "device", name, "path", confPath, "aps", len(cfg.AccessPoints))

	// 直接拉起 wpa_supplicant（nl80211 驱动）。init-agnostic。
	runSupplicant(name, "nl80211", confPath)
}

// buildWifiSupplicantConf 渲染 wpa_supplicant.conf：头部 + 每个 access-point 一个 network 块。
func buildWifiSupplicantConf(cfg *config.Wifi) string {
	var b strings.Builder
	b.WriteString("# Generated by netcfg\n")
	b.WriteString("ctrl_interface=/run/wpa_supplicant\n")
	if cfg.RegulatoryDomain != "" {
		b.WriteString("country=" + cfg.RegulatoryDomain + "\n")
	}
	for _, ssid := range sortedKeys(cfg.AccessPoints) {
		writeAPNetwork(&b, ssid, cfg.AccessPoints[ssid])
	}
	return b.String()
}

// writeAPNetwork 渲染单个 access-point 的 network={} 块。
func writeAPNetwork(b *strings.Builder, ssid string, ap *config.AccessPoint) {
	b.WriteString("network={\n")
	b.WriteString("\tssid=\"" + ssid + "\"\n")

	// 模式：infrastructure 默认（不写 mode）；adhoc=1；ap=2
	switch strings.ToLower(ap.Mode) {
	case "adhoc":
		b.WriteString("\tmode=1\n")
	case "ap":
		b.WriteString("\tmode=2\n")
	}
	if ap.BSSID != "" {
		b.WriteString("\tbssid=" + ap.BSSID + "\n")
	}
	if ap.Hidden {
		b.WriteString("\tscan_ssid=1\n")
	}

	// 鉴权：password 是 psk 简写；否则看 auth.key-management
	km := "psk"
	if ap.Auth != nil && ap.Auth.KeyManagement != "" {
		km = strings.ToLower(ap.Auth.KeyManagement)
	} else if ap.Password == "" {
		km = "none" // 无密码且无 auth → 开放网络
	}

	switch {
	case km == "none":
		b.WriteString("\tkey_mgmt=NONE\n")
	case km == "sae": // WPA3 个人
		b.WriteString("\tkey_mgmt=SAE\n")
		if pw := apPassword(ap); pw != "" {
			b.WriteString("\tsae_password=\"" + pw + "\"\n")
		}
	case strings.HasPrefix(km, "eap"): // 企业
		b.WriteString("\tkey_mgmt=WPA-EAP\n")
		if ap.Auth != nil {
			writeEAPFields(b, ap.Auth)
		}
	default: // psk / psk-sha256
		if pw := apPassword(ap); pw != "" {
			b.WriteString("\tpsk=\"" + pw + "\"\n")
		} else {
			b.WriteString("\tkey_mgmt=NONE\n")
		}
	}

	b.WriteString("}\n")
}

// apPassword 取 AP 的口令：优先 password 简写，否则 auth.password。
func apPassword(ap *config.AccessPoint) string {
	if ap.Password != "" {
		return ap.Password
	}
	if ap.Auth != nil {
		return ap.Auth.Password
	}
	return ""
}
